[variables]
PYTHON_VERSION = "3.11"

[phases.setup]
commands = [
  "poetry install --no-dev --no-interactive --no-ansi"
]

[phases.build]
commands = [
  "echo 'Build phase completed.'"
]

[phases.start]
cmd = "poetry run uvicorn app.main:app --host 0.0.0.0 --port 8000 --workers 2"

[environment]
PORT = "8000"
